---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-inference
  labels:
    team: inference
    kueue.openshift.io/managed: "true"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  name: ml-inference-queue
  namespace: ml-inference
spec:
  # Reference to the ClusterQueue this LocalQueue maps to
  clusterQueue: cluster-total
