---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-training
  labels:
    team: training
    kueue.openshift.io/managed: "true"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  name: ml-training-queue
  namespace: ml-training
spec:
  # Reference to the ClusterQueue this LocalQueue maps to
  clusterQueue: cluster-total
